import type { Option } from "@/constants/commerce";
import type {
  EmailCampaign,
  EmailContact,
  EmailContactStatus,
  EmailTemplate,
  EmailTemplateCategory,
  EngagementLevel,
} from "@/types/email";

/**
 * Email module data.
 *
 * Rates are computed from these counts rather than stored beside them, so a
 * hand-edited fixture cannot claim a 62% open rate on 2,430 sends and 40
 * opens. `openRate` on a template is the exception — it is an average across
 * campaigns this fixture set does not model individually.
 */

/* -------------------------------------------------------------------------- */
/* Options                                                                    */
/* -------------------------------------------------------------------------- */

export const EMAIL_TEMPLATE_CATEGORIES: Option<EmailTemplateCategory>[] = [
  { value: "welcome", label: "Welcome" },
  { value: "newsletter", label: "Newsletter" },
  { value: "promotion", label: "Promotion" },
  { value: "product-launch", label: "Product Launch" },
  { value: "abandoned-cart", label: "Abandoned Cart" },
  { value: "follow-up", label: "Follow-up" },
  { value: "re-engagement", label: "Re-engagement" },
];

export const EMAIL_CONTACT_STATUSES: Option<EmailContactStatus>[] = [
  { value: "subscribed", label: "Subscribed" },
  { value: "pending", label: "Pending confirmation" },
  { value: "unsubscribed", label: "Unsubscribed" },
  { value: "bounced", label: "Bounced" },
];

export const ENGAGEMENT_LEVELS: Option<EngagementLevel>[] = [
  { value: "high", label: "Highly engaged" },
  { value: "medium", label: "Moderately engaged" },
  { value: "low", label: "Rarely engaged" },
  { value: "none", label: "Never engaged" },
];

export const EMAIL_SOURCES = [
  "Storefront signup",
  "Checkout",
  "Lead form",
  "Imported list",
  "Webinar",
  "Referral",
];

export const EMAIL_TAGS = [
  "Newsletter",
  "Customer",
  "VIP",
  "Lead",
  "Wholesale",
  "Webinar",
  "Trial",
];

export const SENDER_IDENTITIES = [
  { value: "hello@marketflow.io", label: "MarketFlow · hello@marketflow.io" },
  { value: "sales@marketflow.io", label: "MarketFlow Sales · sales@marketflow.io" },
  { value: "support@marketflow.io", label: "MarketFlow Support · support@marketflow.io" },
];

/* -------------------------------------------------------------------------- */
/* Campaigns                                                                  */
/* -------------------------------------------------------------------------- */

export const EMAIL_CAMPAIGNS: EmailCampaign[] = [
  {
    id: "em-autumn-newsletter",
    name: "September Newsletter",
    subject: "What's new this month at MarketFlow",
    previewText: "Three new automations, one big pricing change.",
    status: "completed",
    segment: "all",
    audienceLabel: "All Contacts",
    audienceSize: 18_420,
    fromName: "MarketFlow",
    fromEmail: "hello@marketflow.io",
    sent: 18_420,
    delivered: 18_064,
    opened: 7_046,
    clicked: 1_842,
    bounced: 356,
    unsubscribed: 84,
    complained: 6,
    revenue: 12_480,
    templateId: "et-newsletter",
    createdAt: "2026-09-01T09:00:00Z",
    scheduledAt: "2026-09-02T08:00:00Z",
  },
  {
    id: "em-back-to-business",
    name: "Back to Business",
    subject: "20% off every plan until 15 September",
    previewText: "Your autumn campaigns, planned in an afternoon.",
    status: "running",
    segment: "leads",
    audienceLabel: "Leads",
    audienceSize: 9_640,
    fromName: "MarketFlow Sales",
    fromEmail: "sales@marketflow.io",
    sent: 6_820,
    delivered: 6_684,
    opened: 2_874,
    clicked: 892,
    bounced: 136,
    unsubscribed: 41,
    complained: 3,
    revenue: 18_240,
    templateId: "et-promotion",
    createdAt: "2026-09-05T11:30:00Z",
    scheduledAt: "2026-09-06T09:00:00Z",
  },
  {
    id: "em-onboarding-day1",
    name: "Onboarding — Day 1",
    subject: "Welcome to MarketFlow, {{first_name}}",
    previewText: "Start with one channel. Here is how.",
    status: "running",
    segment: "new-customers",
    audienceLabel: "New Customers",
    audienceSize: 1_248,
    fromName: "MarketFlow",
    fromEmail: "hello@marketflow.io",
    sent: 1_248,
    delivered: 1_236,
    opened: 892,
    clicked: 384,
    bounced: 12,
    unsubscribed: 4,
    complained: 0,
    revenue: 4_820,
    templateId: "et-welcome",
    createdAt: "2026-08-28T08:15:00Z",
  },
  {
    id: "em-cart-recovery",
    name: "Basket Reminder",
    subject: "You left something behind",
    previewText: "Still available — we held it for you.",
    status: "running",
    segment: "custom",
    audienceLabel: "Abandoned Checkouts",
    audienceSize: 2_140,
    fromName: "MarketFlow",
    fromEmail: "hello@marketflow.io",
    sent: 1_684,
    delivered: 1_662,
    opened: 812,
    clicked: 346,
    bounced: 22,
    unsubscribed: 9,
    complained: 1,
    revenue: 14_620,
    templateId: "et-abandoned-cart",
    createdAt: "2026-08-24T13:40:00Z",
  },
  {
    id: "em-product-launch",
    name: "Automation Builder Launch",
    subject: "Build a follow-up sequence in five minutes",
    previewText: "The visual builder is live for every plan.",
    status: "completed",
    segment: "customers",
    audienceLabel: "Customers",
    audienceSize: 4_280,
    fromName: "MarketFlow",
    fromEmail: "hello@marketflow.io",
    sent: 4_280,
    delivered: 4_212,
    opened: 2_148,
    clicked: 786,
    bounced: 68,
    unsubscribed: 22,
    complained: 2,
    revenue: 21_840,
    templateId: "et-product-launch",
    createdAt: "2026-08-18T10:00:00Z",
    scheduledAt: "2026-08-19T09:00:00Z",
  },
  {
    id: "em-winback",
    name: "We miss you",
    subject: "Your workspace is still here",
    previewText: "Pick up where you left off — nothing was deleted.",
    status: "completed",
    segment: "custom",
    audienceLabel: "Inactive 90 days",
    audienceSize: 3_460,
    fromName: "MarketFlow",
    fromEmail: "hello@marketflow.io",
    sent: 3_460,
    delivered: 3_284,
    opened: 986,
    clicked: 214,
    bounced: 176,
    unsubscribed: 118,
    complained: 8,
    revenue: 6_240,
    templateId: "et-re-engagement",
    createdAt: "2026-08-12T14:20:00Z",
    scheduledAt: "2026-08-13T10:00:00Z",
  },
  {
    id: "em-webinar-invite",
    name: "October Webinar Invite",
    subject: "Live: WhatsApp automation that actually converts",
    previewText: "Thursday 8 October, 15:00 GMT. Free.",
    status: "scheduled",
    segment: "leads",
    audienceLabel: "Leads",
    audienceSize: 9_640,
    fromName: "MarketFlow",
    fromEmail: "hello@marketflow.io",
    sent: 0,
    delivered: 0,
    opened: 0,
    clicked: 0,
    bounced: 0,
    unsubscribed: 0,
    complained: 0,
    revenue: 0,
    templateId: "et-newsletter",
    createdAt: "2026-09-07T15:20:00Z",
    scheduledAt: "2026-09-24T13:00:00Z",
  },
  {
    id: "em-vip-preview",
    name: "VIP Autumn Preview",
    subject: "First look, before anyone else",
    previewText: "Members-only pricing on the Business plan.",
    status: "scheduled",
    segment: "vip",
    audienceLabel: "VIP Customers",
    audienceSize: 318,
    fromName: "MarketFlow",
    fromEmail: "hello@marketflow.io",
    sent: 0,
    delivered: 0,
    opened: 0,
    clicked: 0,
    bounced: 0,
    unsubscribed: 0,
    complained: 0,
    revenue: 0,
    templateId: "et-product-launch",
    createdAt: "2026-09-06T09:40:00Z",
    scheduledAt: "2026-09-12T08:00:00Z",
  },
  {
    id: "em-feedback-survey",
    name: "Post-purchase Survey",
    subject: "How did we do, {{first_name}}?",
    previewText: "Two questions, thirty seconds.",
    status: "paused",
    segment: "new-customers",
    audienceLabel: "New Customers",
    audienceSize: 1_248,
    fromName: "MarketFlow Support",
    fromEmail: "support@marketflow.io",
    sent: 486,
    delivered: 480,
    opened: 212,
    clicked: 96,
    bounced: 6,
    unsubscribed: 3,
    complained: 0,
    revenue: 0,
    templateId: "et-follow-up",
    createdAt: "2026-08-30T11:10:00Z",
  },
  {
    id: "em-spring-clearance",
    name: "End of Season Clearance",
    subject: "Last chance on summer pricing",
    previewText: "Prices go back up on Monday.",
    status: "failed",
    segment: "all",
    audienceLabel: "All Contacts",
    audienceSize: 18_420,
    fromName: "MarketFlow",
    fromEmail: "hello@marketflow.io",
    sent: 380,
    delivered: 0,
    opened: 0,
    clicked: 0,
    bounced: 380,
    unsubscribed: 0,
    complained: 0,
    revenue: 0,
    templateId: "et-promotion",
    createdAt: "2026-08-22T09:40:00Z",
    scheduledAt: "2026-08-23T08:00:00Z",
  },
  {
    id: "em-referral-push",
    name: "Referral Programme",
    subject: "Give $50, get $50",
    previewText: "Your link is ready.",
    status: "draft",
    segment: "customers",
    audienceLabel: "Customers",
    audienceSize: 4_280,
    fromName: "MarketFlow",
    fromEmail: "hello@marketflow.io",
    sent: 0,
    delivered: 0,
    opened: 0,
    clicked: 0,
    bounced: 0,
    unsubscribed: 0,
    complained: 0,
    revenue: 0,
    createdAt: "2026-09-08T07:30:00Z",
  },
  {
    id: "em-price-change",
    name: "Pricing Update Notice",
    subject: "A small change to your plan from 1 October",
    previewText: "No action needed. Here is what changes.",
    status: "draft",
    segment: "customers",
    audienceLabel: "Customers",
    audienceSize: 4_280,
    fromName: "MarketFlow",
    fromEmail: "hello@marketflow.io",
    sent: 0,
    delivered: 0,
    opened: 0,
    clicked: 0,
    bounced: 0,
    unsubscribed: 0,
    complained: 0,
    revenue: 0,
    createdAt: "2026-09-04T16:05:00Z",
  },
];

/** Totals across the email campaigns, for the stat row. */
export function emailTotals(campaigns: EmailCampaign[]) {
  return campaigns.reduce(
    (totals, campaign) => ({
      sent: totals.sent + campaign.sent,
      delivered: totals.delivered + campaign.delivered,
      opened: totals.opened + campaign.opened,
      clicked: totals.clicked + campaign.clicked,
      bounced: totals.bounced + campaign.bounced,
      unsubscribed: totals.unsubscribed + campaign.unsubscribed,
      revenue: totals.revenue + campaign.revenue,
    }),
    {
      sent: 0,
      delivered: 0,
      opened: 0,
      clicked: 0,
      bounced: 0,
      unsubscribed: 0,
      revenue: 0,
    },
  );
}

/* -------------------------------------------------------------------------- */
/* Templates                                                                  */
/* -------------------------------------------------------------------------- */

export const EMAIL_TEMPLATES: EmailTemplate[] = [
  {
    id: "et-welcome",
    name: "Welcome Series — Day 1",
    description: "First message after signup. One call to action, nothing else.",
    category: "welcome",
    status: "published",
    subject: "Welcome to MarketFlow, {{first_name}}",
    previewText: "Start with one channel. Here is how.",
    blocks: [
      { id: "b1", type: "logo", content: "MarketFlow" },
      { id: "b2", type: "heading", content: "Welcome aboard, {{first_name}}" },
      {
        id: "b3",
        type: "text",
        content:
          "Your workspace is ready. Most teams start by connecting WhatsApp — it takes about two minutes and everything else builds on it.",
      },
      { id: "b4", type: "button", content: "Connect WhatsApp", meta: "/dashboard/integrations/whatsapp" },
      { id: "b5", type: "divider", content: "" },
      { id: "b6", type: "footer", content: "MarketFlow · Unsubscribe · Manage preferences" },
    ],
    usageCount: 24,
    openRate: 71.8,
    updatedAt: "2026-08-28T08:15:00Z",
  },
  {
    id: "et-newsletter",
    name: "Monthly Newsletter",
    description: "Three-story layout with a header image and a product footer.",
    category: "newsletter",
    status: "published",
    subject: "What's new this month at MarketFlow",
    previewText: "Three new automations, one big pricing change.",
    blocks: [
      { id: "b1", type: "logo", content: "MarketFlow" },
      { id: "b2", type: "image", content: "Header banner", meta: "1200 × 400" },
      { id: "b3", type: "heading", content: "September at a glance" },
      { id: "b4", type: "text", content: "The three things worth your time this month." },
      { id: "b5", type: "products", content: "Featured plans", meta: "3 items" },
      { id: "b6", type: "button", content: "Read the changelog", meta: "/changelog" },
      { id: "b7", type: "social", content: "Follow us", meta: "4 platforms" },
      { id: "b8", type: "footer", content: "MarketFlow · Unsubscribe · Manage preferences" },
    ],
    usageCount: 12,
    openRate: 39.0,
    updatedAt: "2026-09-01T09:00:00Z",
  },
  {
    id: "et-promotion",
    name: "Seasonal Promotion",
    description: "Discount-led layout. Offer above the fold, terms in the footer.",
    category: "promotion",
    status: "published",
    subject: "20% off every plan until {{end_date}}",
    previewText: "Your autumn campaigns, planned in an afternoon.",
    blocks: [
      { id: "b1", type: "logo", content: "MarketFlow" },
      { id: "b2", type: "heading", content: "20% off, until {{end_date}}" },
      { id: "b3", type: "image", content: "Offer banner", meta: "1200 × 600" },
      {
        id: "b4",
        type: "text",
        content: "Applies to every plan, new and existing. No code needed.",
      },
      { id: "b5", type: "button", content: "Claim the discount", meta: "/pricing" },
      { id: "b6", type: "footer", content: "Terms apply · Unsubscribe" },
    ],
    usageCount: 18,
    openRate: 42.1,
    updatedAt: "2026-09-05T11:30:00Z",
  },
  {
    id: "et-product-launch",
    name: "Product Launch",
    description: "One feature, three benefits, one button.",
    category: "product-launch",
    status: "published",
    subject: "Introducing {{product}}",
    previewText: "The visual builder is live for every plan.",
    blocks: [
      { id: "b1", type: "logo", content: "MarketFlow" },
      { id: "b2", type: "heading", content: "Introducing {{product}}" },
      { id: "b3", type: "image", content: "Product screenshot", meta: "1200 × 750" },
      {
        id: "b4",
        type: "text",
        content: "Drag a trigger, drop an action, publish. No branching syntax to learn.",
      },
      { id: "b5", type: "button", content: "See it in action", meta: "/features#automation" },
      { id: "b6", type: "divider", content: "" },
      { id: "b7", type: "footer", content: "MarketFlow · Unsubscribe" },
    ],
    usageCount: 9,
    openRate: 50.2,
    updatedAt: "2026-08-18T10:00:00Z",
  },
  {
    id: "et-abandoned-cart",
    name: "Abandoned Basket",
    description: "Product block pulled from the order, with a single recovery link.",
    category: "abandoned-cart",
    status: "published",
    subject: "You left something behind",
    previewText: "Still available — we held it for you.",
    blocks: [
      { id: "b1", type: "logo", content: "MarketFlow" },
      { id: "b2", type: "heading", content: "Still interested, {{first_name}}?" },
      { id: "b3", type: "products", content: "Basket contents", meta: "Dynamic" },
      { id: "b4", type: "button", content: "Complete your order", meta: "{{checkout_url}}" },
      { id: "b5", type: "footer", content: "MarketFlow · Unsubscribe" },
    ],
    usageCount: 31,
    openRate: 48.9,
    updatedAt: "2026-08-24T13:40:00Z",
  },
  {
    id: "et-follow-up",
    name: "Post-purchase Follow-up",
    description: "Two-question survey with a rating row.",
    category: "follow-up",
    status: "published",
    subject: "How did we do, {{first_name}}?",
    previewText: "Two questions, thirty seconds.",
    blocks: [
      { id: "b1", type: "logo", content: "MarketFlow" },
      { id: "b2", type: "heading", content: "How did we do?" },
      { id: "b3", type: "text", content: "Order {{order_id}} arrived on {{delivery_date}}." },
      { id: "b4", type: "button", content: "Leave feedback", meta: "{{survey_url}}" },
      { id: "b5", type: "footer", content: "MarketFlow · Unsubscribe" },
    ],
    usageCount: 14,
    openRate: 44.2,
    updatedAt: "2026-08-30T11:10:00Z",
  },
  {
    id: "et-re-engagement",
    name: "Win-back",
    description: "For contacts with no open in 90 days. Short, no imagery.",
    category: "re-engagement",
    status: "published",
    subject: "Your workspace is still here",
    previewText: "Pick up where you left off — nothing was deleted.",
    blocks: [
      { id: "b1", type: "logo", content: "MarketFlow" },
      { id: "b2", type: "heading", content: "Nothing was deleted" },
      {
        id: "b3",
        type: "text",
        content:
          "Your contacts, templates and automations are exactly where you left them. Come back whenever you are ready.",
      },
      { id: "b4", type: "button", content: "Open my workspace", meta: "/dashboard" },
      { id: "b5", type: "footer", content: "Prefer fewer emails? Manage preferences" },
    ],
    usageCount: 7,
    openRate: 28.5,
    updatedAt: "2026-08-12T14:20:00Z",
  },
  {
    id: "et-welcome-day3",
    name: "Welcome Series — Day 3",
    description: "Second touch. Introduces templates once the channel is live.",
    category: "welcome",
    status: "draft",
    subject: "Your first campaign, in three steps",
    previewText: "Pick a template, pick an audience, send.",
    blocks: [
      { id: "b1", type: "logo", content: "MarketFlow" },
      { id: "b2", type: "heading", content: "Your first campaign" },
      { id: "b3", type: "text", content: "Pick a template, pick an audience, send." },
      { id: "b4", type: "button", content: "Browse templates", meta: "/dashboard/marketing/email/templates" },
      { id: "b5", type: "footer", content: "MarketFlow · Unsubscribe" },
    ],
    usageCount: 0,
    openRate: 0,
    updatedAt: "2026-09-07T10:25:00Z",
  },
  {
    id: "et-black-friday",
    name: "Black Friday",
    description: "High-contrast promotional layout with a countdown block.",
    category: "promotion",
    status: "draft",
    subject: "Black Friday: 40% off annual plans",
    previewText: "Our biggest discount of the year, for four days.",
    blocks: [
      { id: "b1", type: "logo", content: "MarketFlow" },
      { id: "b2", type: "heading", content: "40% off annual plans" },
      { id: "b3", type: "image", content: "Black Friday banner", meta: "1200 × 600" },
      { id: "b4", type: "button", content: "Get the deal", meta: "/pricing" },
      { id: "b5", type: "footer", content: "Ends 1 December · Unsubscribe" },
    ],
    usageCount: 0,
    openRate: 0,
    updatedAt: "2026-09-03T14:50:00Z",
  },
];

/* -------------------------------------------------------------------------- */
/* Contacts                                                                   */
/* -------------------------------------------------------------------------- */

export const EMAIL_CONTACTS: EmailContact[] = [
  {
    id: "ec-sarah",
    firstName: "Sarah",
    lastName: "Ahmed",
    email: "sarah@brightretail.co",
    company: "Bright Retail",
    tags: ["Customer", "VIP", "Newsletter"],
    status: "subscribed",
    engagement: "high",
    source: "Checkout",
    opens: 148,
    clicks: 42,
    campaigns: 36,
    lastActivityAt: "2026-09-08T09:12:00Z",
    createdAt: "2025-11-14T09:00:00Z",
  },
  {
    id: "ec-john",
    firstName: "John",
    lastName: "Smith",
    email: "john@smithagency.io",
    company: "Smith Agency",
    tags: ["Lead", "Webinar"],
    status: "subscribed",
    engagement: "medium",
    source: "Webinar",
    opens: 22,
    clicks: 6,
    campaigns: 14,
    lastActivityAt: "2026-09-07T14:40:00Z",
    createdAt: "2026-05-12T15:20:00Z",
  },
  {
    id: "ec-maria",
    firstName: "Maria",
    lastName: "Gomez",
    email: "maria@casaverde.mx",
    company: "Casa Verde",
    tags: ["Customer", "Newsletter"],
    status: "subscribed",
    engagement: "high",
    source: "Storefront signup",
    opens: 96,
    clicks: 31,
    campaigns: 28,
    lastActivityAt: "2026-09-08T08:05:00Z",
    createdAt: "2026-02-03T11:45:00Z",
  },
  {
    id: "ec-omar",
    firstName: "Omar",
    lastName: "Haddad",
    email: "omar@haddadtrading.ae",
    company: "Haddad Trading",
    tags: ["Customer", "VIP", "Wholesale"],
    status: "subscribed",
    engagement: "high",
    source: "Referral",
    opens: 184,
    clicks: 58,
    campaigns: 41,
    lastActivityAt: "2026-09-06T17:12:00Z",
    createdAt: "2025-08-22T08:30:00Z",
  },
  {
    id: "ec-priya",
    firstName: "Priya",
    lastName: "Nair",
    email: "priya@nairclinics.in",
    company: "Nair Clinics",
    tags: ["Customer"],
    status: "subscribed",
    engagement: "medium",
    source: "Lead form",
    opens: 41,
    clicks: 9,
    campaigns: 22,
    lastActivityAt: "2026-09-04T11:20:00Z",
    createdAt: "2026-01-19T13:10:00Z",
  },
  {
    id: "ec-david",
    firstName: "David",
    lastName: "Chen",
    email: "david@chenstudio.com",
    company: "Chen Studio",
    tags: ["Trial"],
    status: "pending",
    engagement: "none",
    source: "Storefront signup",
    opens: 0,
    clicks: 0,
    campaigns: 1,
    lastActivityAt: "2026-09-08T07:36:00Z",
    createdAt: "2026-09-08T07:30:00Z",
  },
  {
    id: "ec-amina",
    firstName: "Amina",
    lastName: "Rahman",
    email: "amina@rahmanfoods.bd",
    company: "Rahman Foods",
    tags: ["Lead"],
    status: "unsubscribed",
    engagement: "low",
    source: "Imported list",
    opens: 4,
    clicks: 0,
    campaigns: 18,
    lastActivityAt: "2026-08-08T14:00:00Z",
    createdAt: "2026-04-02T09:15:00Z",
  },
  {
    id: "ec-lucas",
    firstName: "Lucas",
    lastName: "Meyer",
    email: "lucas@meyerbau.de",
    company: "Meyer Bau",
    tags: ["Customer", "Newsletter"],
    status: "subscribed",
    engagement: "medium",
    source: "Checkout",
    opens: 62,
    clicks: 14,
    campaigns: 31,
    lastActivityAt: "2026-09-05T14:10:00Z",
    createdAt: "2025-12-11T16:40:00Z",
  },
  {
    id: "ec-hannah",
    firstName: "Hannah",
    lastName: "Park",
    email: "hannah@parkbeauty.kr",
    company: "Park Beauty",
    tags: ["Customer"],
    status: "bounced",
    engagement: "low",
    source: "Imported list",
    opens: 8,
    clicks: 1,
    campaigns: 12,
    lastActivityAt: "2026-08-28T10:15:00Z",
    createdAt: "2026-03-07T12:20:00Z",
  },
  {
    id: "ec-tomas",
    firstName: "Tomás",
    lastName: "Silva",
    email: "tomas@silvamoveis.br",
    company: "Silva Móveis",
    tags: ["Customer", "Wholesale"],
    status: "subscribed",
    engagement: "high",
    source: "Referral",
    opens: 112,
    clicks: 38,
    campaigns: 34,
    lastActivityAt: "2026-09-07T09:00:00Z",
    createdAt: "2025-10-30T07:50:00Z",
  },
  {
    id: "ec-fatima",
    firstName: "Fatima",
    lastName: "Zahra",
    email: "fatima@zahratextiles.ma",
    company: "Zahra Textiles",
    tags: ["Lead", "Wholesale"],
    status: "subscribed",
    engagement: "low",
    source: "Lead form",
    opens: 6,
    clicks: 1,
    campaigns: 9,
    lastActivityAt: "2026-08-26T11:30:00Z",
    createdAt: "2026-05-19T08:00:00Z",
  },
  {
    id: "ec-noah",
    firstName: "Noah",
    lastName: "Bennett",
    email: "noah@bennettco.au",
    company: "Bennett & Co",
    tags: ["Trial", "Webinar"],
    status: "subscribed",
    engagement: "medium",
    source: "Webinar",
    opens: 18,
    clicks: 7,
    campaigns: 6,
    lastActivityAt: "2026-09-06T16:05:00Z",
    createdAt: "2026-08-21T14:25:00Z",
  },
  {
    id: "ec-yuki",
    firstName: "Yuki",
    lastName: "Tanaka",
    email: "yuki@tanakadesign.jp",
    company: "Tanaka Design",
    tags: ["Lead"],
    status: "subscribed",
    engagement: "none",
    source: "Imported list",
    opens: 0,
    clicks: 0,
    campaigns: 11,
    lastActivityAt: "2026-06-30T09:10:00Z",
    createdAt: "2026-03-25T10:40:00Z",
  },
  {
    id: "ec-elena",
    firstName: "Elena",
    lastName: "Rossi",
    email: "elena@rossiatelier.it",
    company: "Rossi Atelier",
    tags: ["Customer", "VIP"],
    status: "subscribed",
    engagement: "high",
    source: "Checkout",
    opens: 134,
    clicks: 46,
    campaigns: 38,
    lastActivityAt: "2026-09-08T06:48:00Z",
    createdAt: "2025-09-18T10:20:00Z",
  },
  {
    id: "ec-marcus",
    firstName: "Marcus",
    lastName: "Obi",
    email: "marcus@obilogistics.ng",
    company: "Obi Logistics",
    tags: ["Lead"],
    status: "subscribed",
    engagement: "medium",
    source: "Lead form",
    opens: 26,
    clicks: 8,
    campaigns: 12,
    lastActivityAt: "2026-09-03T13:15:00Z",
    createdAt: "2026-06-11T09:35:00Z",
  },
  {
    id: "ec-sofia",
    firstName: "Sofia",
    lastName: "Lindqvist",
    email: "sofia@lindqvisthem.se",
    company: "Lindqvist Hem",
    tags: ["Customer", "Newsletter"],
    status: "subscribed",
    engagement: "medium",
    source: "Storefront signup",
    opens: 54,
    clicks: 12,
    campaigns: 24,
    lastActivityAt: "2026-09-02T15:40:00Z",
    createdAt: "2026-01-08T11:00:00Z",
  },
  {
    id: "ec-rahul",
    firstName: "Rahul",
    lastName: "Verma",
    email: "rahul@vermatutors.in",
    company: "Verma Tutors",
    tags: ["Trial"],
    status: "pending",
    engagement: "none",
    source: "Storefront signup",
    opens: 0,
    clicks: 0,
    campaigns: 1,
    lastActivityAt: "2026-09-07T19:20:00Z",
    createdAt: "2026-09-07T19:14:00Z",
  },
  {
    id: "ec-clara",
    firstName: "Clara",
    lastName: "Dupont",
    email: "clara@dupontfleurs.fr",
    company: "Dupont Fleurs",
    tags: ["Customer"],
    status: "unsubscribed",
    engagement: "low",
    source: "Checkout",
    opens: 11,
    clicks: 2,
    campaigns: 19,
    lastActivityAt: "2026-07-22T08:30:00Z",
    createdAt: "2026-02-27T13:45:00Z",
  },
];

export const emailContactName = (contact: EmailContact) =>
  `${contact.firstName} ${contact.lastName}`.trim();

/* -------------------------------------------------------------------------- */
/* Analytics series                                                           */
/* -------------------------------------------------------------------------- */

export const EMAIL_DAY_LABELS = [
  "Aug 12",
  "Aug 15",
  "Aug 18",
  "Aug 21",
  "Aug 24",
  "Aug 27",
  "Aug 30",
  "Sep 2",
  "Sep 5",
  "Sep 8",
];

export const EMAIL_SERIES = {
  sent: [3_460, 2_180, 4_280, 1_940, 2_640, 1_820, 2_240, 18_420, 6_820, 4_120],
  opened: [986, 842, 2_148, 764, 1_212, 698, 918, 7_046, 2_874, 1_684],
  clicked: [214, 268, 786, 296, 512, 224, 386, 1_842, 892, 604],
  /** Percentages, so the rate chart is not derived from two scales at once. */
  openRate: [30.0, 38.6, 51.0, 39.4, 45.9, 38.4, 41.0, 39.0, 43.0, 40.9],
  clickRate: [6.5, 12.3, 18.7, 15.3, 19.4, 12.3, 17.2, 10.2, 13.3, 14.7],
  bounceRate: [5.1, 2.4, 1.6, 1.9, 1.3, 1.4, 1.2, 1.9, 2.0, 1.7],
};

/** Where opens happen. Drives the device split donut. */
export const EMAIL_DEVICE_SPLIT = [
  { label: "Mobile", value: 24_180 },
  { label: "Desktop", value: 11_640 },
  { label: "Tablet", value: 2_788 },
];

/** Opens by hour bucket, for the "best send time" panel. */
export const EMAIL_SEND_TIMES = [
  { label: "06:00–09:00", rate: 34.2 },
  { label: "09:00–12:00", rate: 48.6 },
  { label: "12:00–15:00", rate: 41.8 },
  { label: "15:00–18:00", rate: 37.4 },
  { label: "18:00–21:00", rate: 29.1 },
];
