import type {
  AudienceSegment,
  Campaign,
  CampaignStatus,
  Conversation,
  MarketingChannel,
} from "@/types/marketing";
import type { Option } from "@/constants/commerce";

/**
 * Placeholder marketing data. Every page reads from here so the module is
 * reviewable without a backend; the shapes match `types/marketing` exactly, so
 * an RTK Query hook can replace an import with no other change.
 */

export const CHANNELS: Option<MarketingChannel>[] = [
  { value: "whatsapp", label: "WhatsApp" },
  { value: "email", label: "Email" },
  { value: "sms", label: "SMS" },
];

export const CAMPAIGN_STATUS_OPTIONS: Option<CampaignStatus>[] = [
  { value: "draft", label: "Draft" },
  { value: "scheduled", label: "Scheduled" },
  { value: "running", label: "Running" },
  { value: "completed", label: "Completed" },
  { value: "paused", label: "Paused" },
  { value: "failed", label: "Failed" },
];

export const AUDIENCES: (Option<AudienceSegment> & { size: number; hint: string })[] = [
  { value: "all", label: "All Contacts", size: 12480, hint: "Everyone who opted in" },
  { value: "customers", label: "Customers", size: 2430, hint: "Has placed at least one order" },
  { value: "leads", label: "Leads", size: 7820, hint: "Engaged, not yet purchased" },
  { value: "new-customers", label: "New Customers", size: 684, hint: "First order in the last 30 days" },
  { value: "vip", label: "VIP Customers", size: 218, hint: "Top 10% by lifetime value" },
  { value: "custom", label: "Custom Segment", size: 0, hint: "Build from filters" },
];

export const TIMEZONES = [
  "Asia/Dhaka",
  "Asia/Dubai",
  "Europe/London",
  "America/New_York",
  "UTC",
];

/* -------------------------------------------------------------------------- */
/* Campaigns                                                                  */
/* -------------------------------------------------------------------------- */

export const CAMPAIGNS: Campaign[] = [
  {
    id: "cmp-summer-2026",
    name: "Summer Sale 2026",
    description: "20% off every service package through June.",
    channel: "whatsapp",
    status: "running",
    segment: "all",
    audienceLabel: "All Contacts",
    audienceSize: 12480,
    sent: 11840,
    delivered: 11652,
    opened: 8420,
    clicked: 2064,
    replies: 1284,
    failed: 188,
    revenue: 18240,
    createdAt: "2026-05-24T09:00:00Z",
    scheduledAt: "2026-05-25T08:00:00Z",
  },
  {
    id: "cmp-product-launch",
    name: "New Product Launch",
    description: "Business Package announcement with early-bird pricing.",
    channel: "email",
    status: "completed",
    segment: "customers",
    audienceLabel: "Customers",
    audienceSize: 2430,
    sent: 2430,
    delivered: 2389,
    opened: 1142,
    clicked: 386,
    replies: 42,
    failed: 41,
    revenue: 14820,
    createdAt: "2026-05-18T11:30:00Z",
    scheduledAt: "2026-05-20T09:00:00Z",
  },
  {
    id: "cmp-reengagement",
    name: "Customer Re-engagement",
    description: "Win back accounts inactive for 60 days.",
    channel: "email",
    status: "running",
    segment: "leads",
    audienceLabel: "Leads",
    audienceSize: 7820,
    sent: 5240,
    delivered: 5088,
    opened: 1884,
    clicked: 512,
    replies: 96,
    failed: 152,
    revenue: 9640,
    createdAt: "2026-05-21T14:10:00Z",
    scheduledAt: "2026-05-22T10:00:00Z",
  },
  {
    id: "cmp-flash-weekend",
    name: "Weekend Flash Sale",
    description: "48-hour offer on the Starter Package.",
    channel: "sms",
    status: "scheduled",
    segment: "new-customers",
    audienceLabel: "New Customers",
    audienceSize: 684,
    sent: 0,
    delivered: 0,
    opened: 0,
    clicked: 0,
    replies: 0,
    failed: 0,
    revenue: 0,
    createdAt: "2026-05-29T16:45:00Z",
    scheduledAt: "2026-06-06T09:00:00Z",
  },
  {
    id: "cmp-vip-preview",
    name: "VIP Early Access",
    description: "Preview of the autumn packages for top accounts.",
    channel: "whatsapp",
    status: "completed",
    segment: "vip",
    audienceLabel: "VIP Customers",
    audienceSize: 218,
    sent: 218,
    delivered: 216,
    opened: 198,
    clicked: 84,
    replies: 62,
    failed: 2,
    revenue: 11400,
    createdAt: "2026-05-12T08:20:00Z",
    scheduledAt: "2026-05-13T07:00:00Z",
  },
  {
    id: "cmp-cart-recovery",
    name: "Abandoned Checkout Recovery",
    description: "Nudge for orders left unpaid after two hours.",
    channel: "whatsapp",
    status: "running",
    segment: "custom",
    audienceLabel: "Custom Segment",
    audienceSize: 1240,
    sent: 964,
    delivered: 951,
    opened: 742,
    clicked: 288,
    replies: 174,
    failed: 13,
    revenue: 6820,
    createdAt: "2026-05-26T10:05:00Z",
    scheduledAt: "2026-05-26T12:00:00Z",
  },
  {
    id: "cmp-onboarding-tips",
    name: "Onboarding Tips Series",
    description: "Five-part sequence for new workspaces.",
    channel: "email",
    status: "paused",
    segment: "new-customers",
    audienceLabel: "New Customers",
    audienceSize: 684,
    sent: 412,
    delivered: 404,
    opened: 210,
    clicked: 68,
    replies: 11,
    failed: 8,
    revenue: 2140,
    createdAt: "2026-05-08T13:00:00Z",
  },
  {
    id: "cmp-delivery-alerts",
    name: "Delivery Status Alerts",
    description: "Transactional shipping updates.",
    channel: "sms",
    status: "completed",
    segment: "customers",
    audienceLabel: "Customers",
    audienceSize: 2430,
    sent: 1842,
    delivered: 1798,
    opened: 0,
    clicked: 0,
    replies: 122,
    failed: 44,
    revenue: 0,
    createdAt: "2026-05-04T07:15:00Z",
    scheduledAt: "2026-05-04T09:00:00Z",
  },
  {
    id: "cmp-spring-clearance",
    name: "Spring Clearance",
    description: "End-of-season pricing on remaining stock.",
    channel: "email",
    status: "failed",
    segment: "all",
    audienceLabel: "All Contacts",
    audienceSize: 12480,
    sent: 380,
    delivered: 0,
    opened: 0,
    clicked: 0,
    replies: 0,
    failed: 380,
    revenue: 0,
    createdAt: "2026-04-28T09:40:00Z",
    scheduledAt: "2026-04-29T08:00:00Z",
  },
  {
    id: "cmp-referral-push",
    name: "Referral Programme Push",
    description: "Ask happy customers to refer a business.",
    channel: "whatsapp",
    status: "draft",
    segment: "vip",
    audienceLabel: "VIP Customers",
    audienceSize: 218,
    sent: 0,
    delivered: 0,
    opened: 0,
    clicked: 0,
    replies: 0,
    failed: 0,
    revenue: 0,
    createdAt: "2026-05-30T08:30:00Z",
  },
  {
    id: "cmp-webinar-invite",
    name: "June Webinar Invite",
    description: "Live session on WhatsApp automation.",
    channel: "email",
    status: "scheduled",
    segment: "leads",
    audienceLabel: "Leads",
    audienceSize: 7820,
    sent: 0,
    delivered: 0,
    opened: 0,
    clicked: 0,
    replies: 0,
    failed: 0,
    revenue: 0,
    createdAt: "2026-05-27T15:20:00Z",
    scheduledAt: "2026-06-11T13:00:00Z",
  },
  {
    id: "cmp-restock-alert",
    name: "Back in Stock Alert",
    description: "Notify the waitlist when stock returns.",
    channel: "sms",
    status: "draft",
    segment: "custom",
    audienceLabel: "Custom Segment",
    audienceSize: 412,
    sent: 0,
    delivered: 0,
    opened: 0,
    clicked: 0,
    replies: 0,
    failed: 0,
    revenue: 0,
    createdAt: "2026-05-30T07:10:00Z",
  },
];

/** Open rate is of delivered, not sent — a bounce was never an opportunity. */
export const rateOf = (part: number, total: number) =>
  total === 0 ? 0 : (part / total) * 100;

/* -------------------------------------------------------------------------- */
/* Channel performance (30 days)                                              */
/* -------------------------------------------------------------------------- */

export const PERFORMANCE_DAYS = [
  "May 1", "May 5", "May 10", "May 15", "May 20", "May 25", "May 30",
];

export const CHANNEL_SERIES: Record<MarketingChannel, number[]> = {
  whatsapp: [2840, 3120, 3480, 3960, 4320, 4680, 5120],
  email: [1920, 2040, 2180, 2260, 2420, 2540, 2680],
  sms: [640, 690, 720, 760, 810, 860, 920],
};

/* -------------------------------------------------------------------------- */
/* WhatsApp inbox                                                             */
/* -------------------------------------------------------------------------- */

export const CONVERSATIONS: Conversation[] = [
  {
    id: "conv-sarah",
    status: "open",
    unread: 2,
    online: true,
    contact: {
      id: "cus-sarah",
      name: "Sarah Ahmed",
      phone: "+880 1711 223344",
      email: "sarah@brightretail.co",
      tags: ["summer-sale", "premium"],
      lifecycle: "customer",
      assignedAgent: "Nadia Karim",
      lastActivityAt: "2026-05-30T09:58:00Z",
      notes: ["Asked about invoicing in BDT.", "Prefers WhatsApp over email."],
    },
    messages: [
      {
        id: "m1",
        direction: "outbound",
        body: "Hi Sarah — the Summer Sale is live, 20% off every package until 30 June.",
        at: "2026-05-30T09:40:00Z",
        state: "read",
      },
      {
        id: "m2",
        direction: "inbound",
        body: "Is the Premium Package available?",
        at: "2026-05-30T09:52:00Z",
      },
      {
        id: "m3",
        direction: "inbound",
        body: "And can I pay by card?",
        at: "2026-05-30T09:56:00Z",
      },
    ],
  },
  {
    id: "conv-john",
    status: "pending",
    unread: 1,
    online: false,
    contact: {
      id: "cus-john",
      name: "John Smith",
      phone: "+44 7700 900123",
      email: "john@smithagency.io",
      tags: ["leads"],
      lifecycle: "lead",
      assignedAgent: "Imran Hossain",
      lastActivityAt: "2026-05-30T09:46:00Z",
      notes: ["Comparing us against two other tools."],
    },
    messages: [
      {
        id: "m1",
        direction: "inbound",
        body: "I want to know the price.",
        at: "2026-05-30T09:46:00Z",
      },
    ],
  },
  {
    id: "conv-maria",
    status: "open",
    unread: 0,
    online: true,
    contact: {
      id: "cus-maria",
      name: "Maria Gomez",
      phone: "+52 155 1234 5678",
      email: "maria@casaverde.mx",
      tags: ["catalog", "business"],
      lifecycle: "customer",
      assignedAgent: "Nadia Karim",
      lastActivityAt: "2026-05-30T09:39:00Z",
      notes: [],
    },
    messages: [
      {
        id: "m1",
        direction: "inbound",
        body: "Can you send me the catalog?",
        at: "2026-05-30T09:35:00Z",
      },
      {
        id: "m2",
        direction: "outbound",
        body: "Of course — here is our current collection: mf.link/c/summer",
        at: "2026-05-30T09:39:00Z",
        state: "delivered",
      },
    ],
  },
  {
    id: "conv-omar",
    status: "resolved",
    unread: 0,
    online: false,
    contact: {
      id: "cus-omar",
      name: "Omar Haddad",
      phone: "+971 50 123 4567",
      email: "omar@haddadtrading.ae",
      tags: ["business", "renewal"],
      lifecycle: "vip",
      assignedAgent: "Imran Hossain",
      lastActivityAt: "2026-05-29T17:12:00Z",
      notes: ["Renewal due 12 July."],
    },
    messages: [
      {
        id: "m1",
        direction: "inbound",
        body: "Order arrived, thank you.",
        at: "2026-05-29T17:05:00Z",
      },
      {
        id: "m2",
        direction: "outbound",
        body: "Glad to hear it. Shout if you need another seat added.",
        at: "2026-05-29T17:12:00Z",
        state: "read",
      },
    ],
  },
  {
    id: "conv-priya",
    status: "pending",
    unread: 3,
    online: false,
    contact: {
      id: "cus-priya",
      name: "Priya Nair",
      phone: "+91 98123 45678",
      email: "priya@nairclinics.in",
      tags: ["templates"],
      lifecycle: "customer",
      lastActivityAt: "2026-05-29T11:20:00Z",
      notes: ["Wants Hindi templates."],
    },
    messages: [
      {
        id: "m1",
        direction: "inbound",
        body: "Do the templates come in Hindi?",
        at: "2026-05-29T11:12:00Z",
      },
      {
        id: "m2",
        direction: "inbound",
        body: "We have about 40 staff who would use it.",
        at: "2026-05-29T11:16:00Z",
      },
      {
        id: "m3",
        direction: "inbound",
        body: "Any bulk pricing?",
        at: "2026-05-29T11:20:00Z",
      },
    ],
  },
];

export const AGENTS = ["Nadia Karim", "Imran Hossain", "Tanvir Alam"];

export const QUICK_REPLIES = [
  "Thanks for reaching out — one moment while I check that.",
  "Yes, that package is available. Would you like the catalog?",
  "Here is our current collection: mf.link/c/summer",
  "Your order is confirmed and on its way.",
];
