"use client";

import { useId, useState } from "react";
import { KeyRound, Loader2, ShieldAlert, ShieldCheck, ShieldOff } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog } from "@/components/ui/dialog";
import { Field, Input } from "@/components/ui/input";
import { TOTP_CONFIG } from "@/constants/settings";
import {
  CAPABILITIES,
  disableTwoFactor,
  regenerateRecoveryCodes,
} from "@/lib/account-service";
import { useAccount, useSecurityState } from "@/lib/account-store";
import { formatDate } from "@/lib/format";

import { DetailList, SettingsSection } from "./settings-section";
import { RecoveryCodes } from "./recovery-codes";
import { TwoFactorSetupDialog } from "./two-factor-setup";

/**
 * Two-factor authentication, in the two states it actually has.
 *
 * Off, it is four lines and one button - a status, a sentence about what it
 * buys you, and the way in. On, the setup UI is *gone*: no QR code, no setup
 * key, nothing to scan. A card that keeps showing the enrolment screen after
 * enrolment is a card that cannot answer the only question somebody opens it
 * to ask, which is whether this is on.
 *
 * Both state changes are gated on a current code, not on a confirm dialog
 * alone. A dialog proves somebody has the tab open; a code proves they have the
 * authenticator. Turning a second factor *off* is exactly as sensitive as
 * turning it on - more so, because it is the step an attacker needs - and it is
 * the one place where "are you sure?" on its own is not a control.
 *
 * Recovery codes are real, generated by `crypto.getRandomValues`, and one of
 * them will genuinely disable two-factor if the authenticator is gone. They are
 * shown once. Regenerating replaces the whole set rather than topping it up,
 * because codes somebody may have written down have to stop working or the
 * regeneration bought nothing.
 */

export function TwoFactorCard() {
  const security = useSecurityState();
  const user = useAccount();

  const [setupOpen, setSetupOpen] = useState(false);
  const [disableOpen, setDisableOpen] = useState(false);
  const [regenerateOpen, setRegenerateOpen] = useState(false);

  const enabled = security.twoFactor === "enabled";

  return (
    <SettingsSection
      id="two-factor"
      title="Two-factor authentication"
      description="Add an extra layer of security to protect your account."
      action={
        <Badge tone={enabled ? "success" : "neutral"}>
          {enabled ? "Enabled" : "Disabled"}
        </Badge>
      }
      bodyClassName="space-y-4"
    >
      {enabled ? (
        <>
          <p className="flex items-start gap-2.5 text-sm text-text-secondary">
            <ShieldCheck className="mt-0.5 size-4.5 shrink-0 text-success" aria-hidden />
            Your account is protected with an authenticator app. You will need a
            code from it, or a recovery code, to turn this off.
          </p>

          <DetailList
            columns={2}
            items={[
              {
                label: "Enabled on",
                value: security.twoFactorEnabledAt
                  ? formatDate(security.twoFactorEnabledAt)
                  : "-",
              },
              {
                label: "Recovery codes",
                value: `${security.recoveryCodesRemaining ?? 0} of ${TOTP_CONFIG.recoveryCodeCount} unused`,
              },
            ]}
          />

          <div className="flex flex-wrap gap-2.5">
            <Button
              variant="outline"
              size="compact"
              onClick={() => setRegenerateOpen(true)}
            >
              <KeyRound aria-hidden />
              Regenerate recovery codes
            </Button>

            <Button
              variant="outline"
              size="compact"
              className="text-error-text"
              onClick={() => setDisableOpen(true)}
            >
              <ShieldOff aria-hidden />
              Disable 2FA
            </Button>
          </div>
        </>
      ) : (
        <>
          <p className="max-w-2xl text-sm text-text-secondary">
            With two-factor on, signing in needs your password and a code from an
            authenticator app on your phone. A stolen password stops being
            enough on its own.
          </p>

          <div className="flex flex-wrap items-center gap-2.5">
            <Button
              disabled={!CAPABILITIES.twoFactor}
              onClick={() => setSetupOpen(true)}
            >
              <ShieldCheck aria-hidden />
              Enable 2FA
            </Button>

            {!CAPABILITIES.twoFactorEnforced ? (
              <p className="text-sm font-medium text-text-muted">
                Enrolment is verified; sign-in enforcement arrives with the
                account service.
              </p>
            ) : null}
          </div>
        </>
      )}

      {/* Rendered outside the enabled/disabled branches on purpose: activation
          flips this card into its enabled state while the dialog is still open
          on its recovery-codes step, and a dialog inside the branch it just
          invalidated would unmount mid-flow, taking the codes with it. */}
      <TwoFactorSetupDialog open={setupOpen} onClose={() => setSetupOpen(false)} />

      <DisableDialog open={disableOpen} onClose={() => setDisableOpen(false)} />

      <RegenerateDialog
        open={regenerateOpen}
        onClose={() => setRegenerateOpen(false)}
        account={user.email}
      />
    </SettingsSection>
  );
}

/* -------------------------------------------------------------------------- */
/* Disable                                                                    */
/* -------------------------------------------------------------------------- */

/**
 * A `Dialog` rather than `ConfirmDialog`.
 *
 * `ConfirmDialog` closes and then calls `onConfirm`, which is right for a
 * synchronous delete and wrong here: this call can fail on a bad code, and a
 * dialog that has already dismissed itself has nowhere to put the failure.
 */
function DisableDialog({
  open,
  onClose,
}: {
  open: boolean;
  onClose: () => void;
}) {
  const id = useId();
  const [code, setCode] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  function close() {
    onClose();
    setTimeout(() => {
      setCode("");
      setError(null);
    }, 200);
  }

  async function confirm() {
    if (busy || code.trim().length === 0) return;

    setBusy(true);
    setError(null);

    const result = await disableTwoFactor(code);
    setBusy(false);

    if (!result.ok) {
      setError(result.error.message);
      return;
    }

    close();
  }

  return (
    <Dialog
      open={open}
      onClose={close}
      title="Disable two-factor authentication?"
      description="This will remove the additional security layer from your account."
      footer={
        <>
          <Button variant="outline" size="compact" onClick={close} disabled={busy}>
            Cancel
          </Button>
          <Button
            variant="danger"
            size="compact"
            onClick={() => void confirm()}
            disabled={busy || code.trim().length === 0}
            aria-busy={busy || undefined}
          >
            {busy ? <Loader2 className="animate-spin" aria-hidden /> : null}
            {busy ? "Disabling…" : "Disable 2FA"}
          </Button>
        </>
      }
    >
      <div className="space-y-4">
        <p className="flex items-start gap-2.5 rounded-panel border border-warning/40 bg-warning-soft px-4 py-3 text-sm font-medium text-warning-text">
          <ShieldAlert className="mt-0.5 size-4.5 shrink-0" aria-hidden />
          Your account will be protected by its password alone. Your recovery
          codes stop working and new ones are issued if you turn this back on.
        </p>

        <Field
          label="Authenticator or recovery code"
          htmlFor={`${id}-code`}
          error={error ?? undefined}
          hint="Proving you still hold the second factor is what stops somebody with your open laptop removing it."
        >
          <Input
            id={`${id}-code`}
            value={code}
            error={Boolean(error)}
            inputMode="text"
            autoComplete="one-time-code"
            className="max-w-56 font-mono tracking-widest"
            onChange={(event) => {
              setCode(event.target.value.trim());
              setError(null);
            }}
          />
        </Field>
      </div>
    </Dialog>
  );
}

/* -------------------------------------------------------------------------- */
/* Regenerate recovery codes                                                  */
/* -------------------------------------------------------------------------- */

function RegenerateDialog({
  open,
  onClose,
  account,
}: {
  open: boolean;
  onClose: () => void;
  account: string;
}) {
  const id = useId();
  const [code, setCode] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [issued, setIssued] = useState<string[] | null>(null);

  function close() {
    onClose();
    setTimeout(() => {
      setCode("");
      setError(null);
      setIssued(null);
    }, 200);
  }

  async function confirm() {
    if (busy || code.length !== TOTP_CONFIG.digits) return;

    setBusy(true);
    setError(null);

    const result = await regenerateRecoveryCodes(code);
    setBusy(false);

    if (!result.ok) {
      setError(result.error.message);
      setCode("");
      return;
    }

    setIssued(result.data);
  }

  return (
    <Dialog
      open={open}
      onClose={close}
      title={issued ? "New recovery codes" : "Regenerate recovery codes"}
      description={
        issued
          ? "Your previous codes no longer work."
          : "Confirm with a code from your authenticator. The old codes stop working immediately."
      }
      footer={
        issued ? (
          <Button size="compact" onClick={close}>
            Done
          </Button>
        ) : (
          <>
            <Button variant="outline" size="compact" onClick={close} disabled={busy}>
              Cancel
            </Button>
            <Button
              size="compact"
              onClick={() => void confirm()}
              disabled={busy || code.length !== TOTP_CONFIG.digits}
              aria-busy={busy || undefined}
            >
              {busy ? <Loader2 className="animate-spin" aria-hidden /> : null}
              {busy ? "Generating…" : "Generate new codes"}
            </Button>
          </>
        )
      }
    >
      {issued ? (
        <RecoveryCodes codes={issued} account={account} />
      ) : (
        <Field
          label="Authenticator code"
          htmlFor={`${id}-code`}
          error={error ?? undefined}
          hint={`${TOTP_CONFIG.digits} digits from your authenticator app.`}
        >
          <Input
            id={`${id}-code`}
            value={code}
            error={Boolean(error)}
            inputMode="numeric"
            autoComplete="one-time-code"
            maxLength={TOTP_CONFIG.digits}
            className="max-w-48 text-center font-mono text-lg tracking-[0.4em]"
            onChange={(event) => {
              setCode(
                event.target.value.replace(/\D/g, "").slice(0, TOTP_CONFIG.digits),
              );
              setError(null);
            }}
          />
        </Field>
      )}
    </Dialog>
  );
}
